name: PR Validation

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8, 11, 17]
    
    steps:
      - name: Checkout kod
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: Sätt upp JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Bygg och installera plugin lokalt
        run: mvn clean install -DskipTests -Dgpg.skip=true
      
      - name: Kör alla tester (unit + integration)
        run: mvn verify -Dgpg.skip=true
      
      - name: Ladda upp test-resultat
        uses: actions/upload-artifact@v4.6.2
        if: failure()
        with:
          name: test-results-jdk-${{ matrix.java-version }}
          path: target/surefire-reports/

  version-bump:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout kod
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: Sätt upp JDK 8
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 8.0.412+8
          distribution: 'adopt'
          
      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          create_annotated_tag: false
          tag_prefix: ''
          default_bump: false
          dry_run: true
          
      - name: Bump version in pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.new_tag }} -Dgpg.skip=true
        
      - name: Final build with Maven
        run: mvn -B package --file pom.xml -DskipTests -Dgpg.skip=true
