name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 1.8
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "central",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_TOKEN }}"
            }]
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Git Automatic Semantic Versioning
        uses: bitshifted/git-auto-semver@v1.1.0
        with:
          main_branch: master
          create_tag: true
      - name: Publish to Maven Central
        run: mvn deploy
