name: Merge to Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 8.0.412+8
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "central",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_TOKEN }}"
            }]

      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          create_annotated_tag: false
          tag_prefix: ''
          default_bump: false
      - name: Bump version in pom.xml
        if: steps.version.outputs.new_tag
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.new_tag }}
      - name: Install
        run: mvn -B clean install -DskipTests --file pom.xml -Ppgp-sign
      - name: Build with Maven
        if: steps.version.outputs.new_tag
        run: mvn -B package --file pom.xml -Ppgp-sign
      - name: Publish to Maven Central
        if: steps.version.outputs.new_tag
        run: mvn deploy
